### ISSUE TITLE
SQL Injection Bug

### ISSUE THREAD

**Issue by ethanwillis** [genenetwork/genenetwork1#2]
There's a security hole that would allow someone to delete or dump all data from the SQL databases backing GeneNetwork. Which means potentially non-public datasets could be taken(if they're hosted on the same system, or one within the same network). 

Using a standard query I got the following stacktrace.  

> Mod_python error: "PythonHandler main"
> Traceback (most recent call last):
> 
>  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
>    result = object(req)
> 
>  File "/gnshare/gn/web/webqtl/main.py", line 75, in handler
>    page = SearchResultPage.SearchResultPage(fd)
> 
>  File "/gnshare/gn/web/webqtl/search/SearchResultPage.py", line 211, in **init**
>    self.nresults = self.executeQuery()
> 
>  File "/gnshare/gn/web/webqtl/search/SearchResultPage.py", line 528, in executeQuery
>    self.cursor.execute(item)
> 
>  File "/usr/lib64/python2.4/site-packages/MySQLdb/cursors.py", line 173, in execute
>    self.errorhandler(self, exc, value)
> 
>  File "/usr/lib64/python2.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>    raise errorclass, errorvalue
> 
> OperationalError: (1054, "Unknown column 'Publish.behavior' in 'where clause'")

In order to replicate this bug run a query from the main page using these options:

> Species: Mouse
> Group: BXD
> Type: Phenotype
> Data Set: BXD Published Phenotypes
> Get Any: 
> Combined: Central nervous system, behavior: Swimming speed during acquisition of task using Morris water maze [cm/s]

Note: if you modify the word "behavior" it will change the output of the stacktrace.

**Comment by sn3twork** [comment]
See my pull request. This fixes the immediate issue found above, but I believe significant work will need to be done in order to make all of the database queries secure throughout the entire applicaiton. https://github.com/genenetwork/genenetwork/pull/3

**Comment by pjotrp** [comment]
https://trello.com/c/x4EtoA6I/263-set-tables-to-read-only
