### ISSUE TITLE
Mapping figure shows large blank area when using Haplotype Analyst with scale set to centimorgan

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork1#33]
This is probably a minor issue since users rarely use centimorgan scale, but I noticed it while trying to compare R/qtl's GN2 results with GN1's map (since R/qtl returns results with centimorgan scale). I imagine the best solution is just to disable the Haplotype Analyst option when the scale is set to centimorgan.

**Comment by pjotrp** [comment]
stale
