### ISSUE TITLE
Database Login Information 

### ISSUE THREAD

**Issue by ethanwillis** [genenetwork/genenetwork1#4]
If I'm reading it correctly the config file at https://github.com/genenetwork/genenetwork/blob/b3a995f010428cdb37691370c5239fbe1e83ac66/web/webqtl/base/webqtlConfig.py

Simply imports the username and database name info from the local config located at 
https://github.com/genenetwork/genenetwork/blob/b3a995f010428cdb37691370c5239fbe1e83ac66/web/webqtl/base/webqtlConfigLocal.py

It looks like the database is being hosted on the same machine as well.. so potentially an attacker could just use the login info in the webqtlConfigLocal in order to connect to the database using whatever db client they wanna use to dump/insert data. 

Passwords will need to be updated, old files purged(see link below) and .gitignores for these files will need to be used in the future. 
 https://help.github.com/articles/remove-sensitive-data/

**Comment by pjotrp** [comment]
https://trello.com/c/x4EtoA6I/263-set-tables-to-read-only
