### ISSUE TITLE
mod_python not creating directory tree in /tmp with guix

### ISSUE THREAD

**Issue by Millak** [genenetwork/genenetwork1#61]
When genenetwork1 is deployed in a guix container mod_python doesn't create the /tmp/mp_sess/[0-z][0-z]/ directory structure as expected.

**Comment by pjotrp** [comment]
I don't think it is a problem. I see session files being written, i.e. `$TMPDIR/4372e73d1cf06bfa355a5e9948b496bde398400e.session`
