### ISSUE TITLE
Directory not found in container

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#64]
```
Traceback (most recent call last):
  File "/gnu/store/r4nb40zfdbl936xdfsj0an37fz9mx528-genenetwork1-0.0.0-2.acf65ac/web/webqtl/cmdLine/webqtlCmdLine.py", line 96, in ?
    page = CorrelationPage.CorrelationPage(fd)
  File "/gnu/store/r4nb40zfdbl936xdfsj0an37fz9mx528-genenetwork1-0.0.0-2.acf65ac/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 251, in __init__
    DirectoryList = os.listdir(webqtlConfig.TEXTDIR)  ### List of existing text files.  Used to check if a text file already exists
OSError: [Errno 2] No such file or directory: '/gnu/store/r4nb40zfdbl936xdfsj0an37fz9mx528-genenetwork1-0.0.0-2.acf65ac/web/ProbeSetFreeze_DataMatrix/'
```

**Comment by pjotrp** [comment]
`ProbeSetFreeze_DataMatrix` is not part of the source tree because of gigantic files. I think I'll need to tarball the source for deployment.

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> `ProbeSetFreeze_DataMatrix` is not part of the
> source tree because of gigantic files. I think
> I'll need to tarball the source for deployment.

This makes a lot of sense. Then we could add it as
part of gn1's input, in a similar way to what we
do with thirdparty.tgz.


-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by pjotrp** [comment]
At the moment I am running the container in the source dir. Good for troubleshooting.

**Comment by pjotrp** [comment]
Solved.
