### ISSUE TITLE
pairscan not working on new GN1

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#77]
>    Here is the error I get trying to run pair-scan.
> Traceback (most recent call last):
>   File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 79, in ?
>     from pairScan import DirectPlotPage
>   File "/gnshare/gn/web/webqtl/cmdLine/../pairScan/DirectPlotPage.py", line 32,
> in ?
>     import direct
> ImportError: No module named direct

**Comment by pjotrp** [comment]
Hi @Millak - can you take a look why this is missing from the GeneNetwork1 package? Tnx!

**Comment by Millak** [comment]
from the traceback it looks like it's in production.

from my gn1-python24-site-packages folder from lily there's a direct.so{,.bak} file so I'll start hunting around to see what I can make of it.

**Comment by pjotrp** [comment]
Tracking progress here

https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/genenetwork1/gn1-pairscan.gmi

**Comment by pjotrp** [comment]
Close
